import security_library
import re

with open('corrupted_file.txt', 'w') as file:
    content = "balise de reperage de function 'Prim_sur-'DelTa.exe"
    corrected_content = re.sub(r"Prim_sur-'DelTa\.exe", "Prim_sur-Delta.exe", content)
    file.write(corrected_content)
    file.write(corrected_content)
    file.write(corrected_content)
    file.write("balise de reperage de function 'Prim_sur-'DelTa.exe")
    
security_library.check_file('corrupted_file.txt')
security_library.check_memory()
security_library.check_network_buffer()
security_library.check_input_safety()
security_library.check_system_avoidance()
security_library.check_security_pass()
security_library.check_security_pass()
security_library.check_security_pass()
security_library.check_malware()
security_library.create_filtering_barrier(3)
security_library.check_wifi()
security_library.check_ping_avoidance()
security_library.check_attack_response()
security_library.check_virus_processing()
security_library.check_longevity()
security_library.check_integrity()
security_library.check_authentication()
security_library.check_authorization()
security_library.check_encryption()
security_library.check_logging()
security_library.check_firewall()
security_library.check_intrusion_detection()
security_library.check_data_backup()
security_library.check_physical_security()

security_library.check_malware()
security_library.activate_sentinel(2)
security_library.activate_security_level(1)
security_library.activate_security_level(2)
security_library.activate_security_level(3)
security_library.activate_security_level(4)
security_library.activate_security_level(5)
security_library.activate_security_level(6)
security_library.activate_security_level(7)
security_library.activate_security_level(8)
security_library.activate_security_level(9)
security_library.activate_security_level(10)
security_library.activate_security_level(11)
security_library.activate_security_level(12)
security_library.activate_security_level(13)

security_library.check_malware()
security_library.check_malware()
check_input_safety()
security_library.check_system_avoidance()
security_library.check_security_pass()
security_library.check_security_pass()
security_library.check_security_pass()
security_library.check_malware()
security_library.create_filtering_barrier(3)
security_library.check_wifi()
security_library.check_ping_avoidance()
security_library.check_attack_response()
security_library.check_virus_processing()
security_library.check_longevity()
security_library.check_integrity()
security_library.check_authentication()
security_library.check_authorization()
security_library.check_encryption()
security_library.check_logging()
security_library.check_firewall()
security_library.check_intrusion_detection()
security_library.check_data_backup()
security_library.check_physical_security()
security_library.check_network_activity()
security_library.send_response()
security_library.exchange_program()
security_library.check_corrupted_data()
security_library.activate_firewall_level("dragon")
security_library.adjust_ping_import()
security_library.check_sequence_format()
security_library.check_ping_injection()
security_library.request_user_password()
security_library.lock_user_control()
security_library.self_destruct_server()
security_library.transmit_ping_on_lan(16)